# -*- coding: utf-8 -*-
"""Students(4190).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v6h5Xasp21rXqO1r2YJAgz6w99_48rIz

Importações das bibliotecas
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

"""Carregar CSV"""

df = pd.read_csv('StudentsPerformance.csv')

df.head()

df.describe()

notas_matematica = df['math score']
notas_leitura = df['reading score']
notas_escrita = df['writing score']

media_matematica = notas_matematica.mean()
media_leitura = notas_leitura.mean()
media_escrita = notas_escrita.mean()
print(f'media_matematica {media_matematica:.2f}')
print(f'media_leitura {media_leitura:.2f}')
print(f'media_escrita {media_escrita:.2f}')

mediana_matematica = notas_matematica.median()
mediana_leitura = notas_leitura.median()
mediana_escrita = notas_escrita.median()
print(f'mediana_matematica {mediana_matematica}')
print(f'mediana_leitura {mediana_leitura}')
print(f'mediana_escrita {mediana_escrita}')

moda_matematica = notas_matematica.mode()
moda_leitura = notas_leitura.mode()
moda_escrita = notas_escrita.mode()
print(f'moda_matematica {moda_matematica[0]}')
print(f'moda_leitura {moda_leitura[0]}')
print(f'moda_escrita {moda_escrita[0]}')

amplitude_matematica = notas_matematica.max() - notas_matematica.min()
amplitude_leitura = notas_leitura.max() - notas_leitura.min()
amplitude_escrita = notas_escrita.max() - notas_escrita.min()
print(f'amplitude_matematica {amplitude_matematica:.2f}')
print(f'amplitude_leitura {amplitude_leitura:.2f}')
print(f'amplitude_escrita {amplitude_escrita:.2f}')

variancia_matematica = notas_matematica.var()
variancia_leitura = notas_leitura.var()
variancia_escrita = notas_escrita.var()
print(f'variancia_matematica {variancia_matematica:.2f}')
print(f'variancia_leitura {variancia_leitura:.2f}')
print(f'variancia_escrita {variancia_escrita:.2f}')

desvio_padrao_matematica = notas_matematica.std()
desvio_padrao_leitura = notas_leitura.std()
desvio_padrao_escrita = notas_escrita.std()
print(f'desvio_padrao_matematica {desvio_padrao_matematica:.2f}')
print(f'desvio_padrao_leitura {desvio_padrao_leitura:.2f}')
print(f'desvio_padrao_escrita {desvio_padrao_escrita:.2f}')

Q1_matematica = notas_matematica.quantile(0.25)
Q2_matematica = notas_matematica.quantile(0.50)
Q3_matematica = notas_matematica.quantile(0.75)
print(f'Q1_matematica {Q1_matematica:.2f}')
print(f'Q2_matematica {Q2_matematica:.2f}')
print(f'Q3_matematica {Q3_matematica:.2f}')

plt.figure(figsize=(10, 6))
sns.scatterplot(x='math score', y='writing score', data=df)
plt.title('Relação entre Notas de Matemática e Escrita')
plt.show()

plt.figure(figsize=(6,4))
sns.boxplot(x='gender', y='math score', data=df)
plt.title('Comparação das Notas de Matemática por Gênero')
plt.show()